### ISSUE TITLE
Feature request: config option to disable movement lock altogether + separately for dungeons

### ISSUE THREAD

**Issue by JTF195** [TybaIt/ValheimMods#1]
Would it be possible to add a couple options to disable the movement lock?

Even with ConsiderAreaLoadedAfterSeconds set to 0 and DecreaseMinLoadTimeByPercent set to 100, there is still a very brief stutter where the movement lock takes effect and then cancels

This is most noticeable with crypts and caves, which load so quickly that the stutter is noticeable (compared to [FasterTeleportation](https://github.com/LVH-IT/Faster-Teleportation) which does not have a movement lock on dungeons)

I would like to disable the movement lock specifically for dungeons, but ideally there should be a separate option to disable it altogether for people who want to live dangerously and believe their PCs and SSDs can handle it.

**Comment by TybaIt** [comment]
Faster Teleportation is 4 lines of code and  does nothing but multiply delta time by 3 (which my mod does by default) that is added onto teleport time so it reaches those minimum load times quicker. The difference is my default configs are set to be a bit saver.

Now, I can disable the movement lock as I previously did in my testing but then you will just be stuck in place anyway and you will see yourself falling for a millisecond before being teleported into place again and again until the process ends. This is because the teleportation process is called each tick and does the freezing of the body tick and  the teleportation each tick until the process ends (load state is fine and minimum load time reached).

You can try and adjust the teleportation speed with the config..

I will look into making it a bit more fluid for dungeons but this will require fiddeling a lot with the teleportation function which can cause other non-portal teleportation to be affected.

**Comment by TybaIt** [comment]
The 4-5 lines of relevant code of [Faster Teleportation](https://github.com/LVH-IT/Faster-Teleportation/blob/d1b2ceeeb55cbd7f24d730f11b8c5e800a799836/FasterTeleportation.cs#L44)
Code of the game:
```csharp
private void UpdateTeleport(float dt)
{
	if (!this.m_teleporting)
	{
		this.m_teleportCooldown += dt;
		return;
	}
	this.m_teleportCooldown = 0f;
	this.m_teleportTimer += dt;
	if (this.m_teleportTimer > 2f)
	{
		Vector3 lookDir = this.m_teleportTargetRot * Vector3.forward;
		base.transform.position = this.m_teleportTargetPos;
		base.transform.rotation = this.m_teleportTargetRot;
		this.m_body.velocity = Vector3.zero;
		this.m_maxAirAltitude = base.transform.position.y;
		base.SetLookDir(lookDir);
		if ((this.m_teleportTimer > 8f || !this.m_distantTeleport) && ZNetScene.instance.IsAreaReady(this.m_teleportTargetPos))
		{
			float num = 0f;
			if (ZoneSystem.instance.FindFloor(this.m_teleportTargetPos, out num))
			{
				this.m_teleportTimer = 0f;
				this.m_teleporting = false;
				base.ResetCloth();
				return;
			}
			if (this.m_teleportTimer > 15f || !this.m_distantTeleport)
			{
				if (this.m_distantTeleport)
				{
					Vector3 position = base.transform.position;
					position.y = ZoneSystem.instance.GetSolidHeight(this.m_teleportTargetPos) + 0.5f;
					base.transform.position = position;
				}
				else
				{
					base.transform.rotation = this.m_teleportFromRot;
					base.transform.position = this.m_teleportFromPos;
					this.m_maxAirAltitude = base.transform.position.y;
					this.Message(MessageHud.MessageType.Center, "$msg_portal_blocked", 0, null);
				}
				this.m_teleportTimer = 0f;
				this.m_teleporting = false;
				base.ResetCloth();
			}
		}
	}
}
```

[Relevant code of Immersive Portals](https://github.com/TybaIt/ValheimMods/blob/7eaea28552a3696262f71f3c6bf2af66c62b1485/ImmersivePortals/Patches/PlayerPatch.cs#L24)

**Comment by JTF195** [comment]
The Pastebin link doesn't seem to be working

In all my testing, I've continued to have ConsiderAreaLoadedAfterSeconds set to 0 and DecreaseMinLoadTimeByPercent set to 100 and the only other mods installed were EquipmentAndQuickSlots and SkToolbox.

I have Valheim on an Optane SSD and I was testing going back and forth into and out of a sunken crypt, so the load times were virtually instant, which is probably the only reason the very brief stutter is even noticeable.

I know this is an extreme edge case, so I appreciate your patience

I'll test 2.7.4

**Comment by TybaIt** [comment]
Please ensure to have logs enabled and check teleport travel time.

**Comment by JTF195** [comment]
Okay. I've done some more testing with logging enabled. This time I used a troll cave, since it doesn't have stairs or a ramp

Config:
  ConsiderAreaLoadedAfterSeconds = 0
  DecreaseMinLoadTimeByPercent = 100

With ImmersivePortals by itself:
- MultiplyDeltaTimeBy = 3, teleporting took 117-128ms
- MultiplyDeltaTimeBy = 10, teleporting took 78-86ms
Incidentally, when fully sprinting, I occasionally got completely stuck on the door (maybe 10-20% of the time) and had to back away and re-enter.

With FasterTeleportation by itself, or with both mods and MultiplyDeltaTimeBy set to either 3 or 10, the teleport time was 35-45ms
(and I did not get stuck on the door in any of those scenarios)

**Comment by TybaIt** [comment]
Fiddeling around with the config so much to force into an area when it's not ready is not risk free. 
Also I'd recommend not to run both mods at the same time.

**Comment by JTF195** [comment]
Distant portals are super risky, and I would strongly prefer to use a safer config for them, but caves, crypts, and nearby portals load almost instantly, and shouldn't be subject to the same restrictions.

When I tested with both mods enabled, they were indeed reporting slightly different load times, but the difference was usually within +/-10ms in either direction. Immersive Portals reported 35-45ms load times as well, and the -40ms difference with FT or both enabled is definitely noticeable (and consistent with my previous tests)

**Comment by TybaIt** [comment]
It is to a 100 percent just your brain because you see the logs which are off by a margin thanks to using DateTime and brain searches for a pattern. Also my logs start a little earlier (when you trigger the teleport) while FT starts it's Stopwatch during the teleport.

**Comment by JTF195** [comment]
You're missing the part where your own mod, with its own logging, reports a 40ms faster load time with both mods enabled. 

[MultiplyDeltaTimeBy = 3](https://i.imgur.com/2qA9UUd.png)
[MultiplyDeltaTimeBy = 10](https://i.imgur.com/c9Pqg79.png)
[Both mods enabled](https://i.imgur.com/c9Pqg79.png)

There is a visible difference, and I have also verified it with recordings.


Before you accuse me of imagining things, maybe actually do your own testing

**Comment by TybaIt** [comment]
Obviously because both mods increase delta time and patch the same method.
